name: SampleWorkflow

# Controls when the workflow will run
on:
    repository_dispatch:
     types: 
      - sampleevent


jobs:
  SampleBuild1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo ${{github.workflow_id}}
      - name: Run a multi-line script
        run: |
          echo "This is from jenkins pipeline "
          echo "sample one"
          echo "added a first line1"
